Repository Trophy198/rustplusplus-credential-page, pull requests merged in 2024-05, with the labels that each got.

#11 add web version 0.1.1
  package-lock.json
  package.json
  src/components/loadingCollection/dot/dot.module.css
  src/components/loadingCollection/dot/index.tsx
  src/components/loadingCollection/spinner/spinner.module.css
  src/components/loadingCollection/spinner/spinner.tsx
  src/components/mainHeader/mainHeader.module.css
  src/components/mainHeader/mainHeader.tsx
  src/components/mainLayout/mainLayout.tsx
  src/hooks/useExtensionDetection.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/callback.ts
  src/pages/api/checkLogin.ts
  src/pages/api/logout.ts
  src/pages/callback/callback.module.css
  src/pages/callback/index.tsx
  src/pages/display/display.module.css
  src/pages/display/index.tsx
  src/pages/index.tsx
  src/store/useAuthStore.ts
  src/styles/Display.module.css
  src/styles/Home.module.css
  src/utils/formatCredentialsData.ts
  tsconfig.json
Labels: enhancement

#9 Create footer component
  public/icons/discord.png
  public/icons/github.png
  src/components/footer/footer.module.css
  src/components/footer/footer.tsx
Labels: enhancement

#19 main page and intersection hook
  .github/pull_request_template.md
  .prettierrc
  package-lock.json
  package.json
  public/images/activity.png
  public/images/background.png
  public/images/eventInfoLogo.png
  public/images/eventNotifications.png
  public/images/rustplusplusLogo.png
  public/images/serverInfoLogo.png
  public/images/serverInformation.png
  public/images/settingsLogo.png
  public/images/smartSwitch.png
  public/images/teamInfoLogo.png
  public/images/teamchat.png
  public/images/trackersChannel.png
  src/components/homepage/extensionSection.tsx
  src/components/homepage/featureSection.tsx
  src/components/homepage/heroSection.tsx
  src/components/mainHeader/mainHeader.module.css
  src/hooks/useIntersectionObserver.tsx
  src/pages/index.tsx
  src/pages/mainpage.module.css
  src/styles/globals.css
  src/utils/formatCredentialsData.ts
  tsconfig.json
Labels: enhancement

#14 create document page and add sidebar component
  src/components/document/layout.module.css
  src/components/document/layout.tsx
  src/components/sidebar/sectionHeader/sectionHeader.module.css
  src/components/sidebar/sectionHeader/sectionHeader.tsx
  src/components/sidebar/sidebar.module.css
  src/components/sidebar/sidebar.tsx
  src/components/sidebar/subMenu/subMenu.module.css
  src/components/sidebar/subMenu/subMenu.tsx
  src/config/menuItems.ts
  src/pages/documents/commands/index.tsx
  src/pages/documents/discord-text-channels/index.tsx
  src/pages/documents/documents.module.css
  src/pages/documents/getting-started/index.tsx
  src/pages/documents/index.tsx
  src/types/sidebarTypes.ts
Labels: enhancement

#34 add HTML-related components to documents page
  src/components/blockquote/blockquote.module.css
  src/components/blockquote/blockquote.tsx
  src/components/document/heading/heading.module.css
  src/components/document/heading/heading.tsx
  src/components/document/heading2/heading2.module.css
  src/components/document/heading2/heading2.tsx
  src/components/document/listItem/listItem.module.css
  src/components/document/listItem/listItem.tsx
  src/components/document/orderedList/orderedList.module.css
  src/components/document/orderedList/orderedList.tsx
  src/components/document/paragraph/paragraph.module.css
  src/components/document/paragraph/paragraph.tsx
  src/components/document/strong/strong.module.css
  src/components/document/strong/strong.tsx
  src/components/document/unorderedList/unorderedList.module.css
  src/components/document/unorderedList/unorderedList.tsx
Labels: enhancement

#27 Create Codeblock component
  src/components/document/code/code.module.css
  src/components/document/code/code.tsx
Labels: enhancement

#41 Ver1.0.2(documents page)
  package.json
  public/images/discordBotSetup/add_bot_to_server_bot_setup.png
  public/images/discordBotSetup/authorise_bot_setup.png
  public/images/discordBotSetup/bot_bot_setup.png
  public/images/discordBotSetup/bot_in_server_bot_setup.png
  public/images/discordBotSetup/bot_permissions_bot_setup.png
  public/images/discordBotSetup/bot_token_bot_setup.png
  public/images/discordBotSetup/copy_application_id_bot_setup.png
  public/images/discordBotSetup/create_an_application_bot_setup.png
  public/images/discordBotSetup/generated_url_bot_setup.png
  public/images/discordBotSetup/new_application_bot_setup.png
  public/images/discordBotSetup/oauth2_bot_setup.png
  public/images/discordBotSetup/privileged_gateway_intents_bot_setup.png
  public/images/discordBotSetup/reset_token_bot_setup.png
  public/images/discordBotSetup/scopes_bot_setup.png
  public/images/discordBotSetup/yes_create_bot_bot_setup.png
  public/images/fcmCredentials/credentials_copy.png
  public/images/fcmCredentials/credentials_discord.png
  public/images/fcmCredentials/fcm_credential_application_connect.png
  public/images/fcmCredentials/steam_login.png
  public/images/fcmCredentials/teammates_paired.png
  public/images/pairAndConnectToServer/pairing_server.png
  public/images/pairAndConnectToServer/servers_channel.png
  src/components/document/layout.module.css
  src/components/document/pages/common.module.css
  src/components/document/pages/discordBotSetup/section.tsx
  src/components/document/pages/fcmCredentials/section.tsx
  src/components/document/pages/pairAndConnectToServer/section.tsx
  src/components/pagination/pagination.module.css
  src/components/pagination/pagination.tsx
  src/data/documents/discordBotSetup/orderedItems.tsx
  src/data/documents/fcmCredentials/unorderedItems.tsx
  src/data/documents/pairAndConnectToServer/orderedItems.tsx
  src/pages/documents/getting-started/discord-bot-setup.tsx
  src/pages/documents/getting-started/fcm-credentials.tsx
  src/pages/documents/getting-started/pair-and-connect-to-a-server.tsx
Labels: enhancement, Version Up

#45 updates and improvements for version 1.0.2
  src/components/document/pages/discordBotSetup/section.tsx
  src/components/document/pages/fcmCredentials/section.tsx
  src/components/document/pages/pairAndConnectToServer/section.tsx
  src/data/documents/discordBotSetup/images.ts
  src/data/documents/discordBotSetup/orderedItems.tsx
  src/data/documents/fcmCredentials/images.ts
  src/data/documents/fcmCredentials/unorderedItems.tsx
  src/data/documents/pairAndConnectToServer/images.ts
  src/data/documents/pairAndConnectToServer/orderedItems.tsx
  src/pages/documents/getting-started/discord-bot-setup.tsx
  src/pages/documents/getting-started/fcm-credentials.tsx
  src/pages/documents/getting-started/pair-and-connect-to-a-server.tsx
  src/styles/globals.css
  src/types/imageUrlTypes.ts
Labels: enhancement

#46 Create discord text channels page
  public/images/discordTextChannels/activityChannel.png
  public/images/discordTextChannels/commandsChannel.png
  public/images/discordTextChannels/eventsChannel.png
  public/images/discordTextChannels/serversChannel.png
  public/images/discordTextChannels/settingsChannel.png
  public/images/discordTextChannels/smartAlarm.png
  public/images/discordTextChannels/smartSwitch.png
  public/images/discordTextChannels/smartSwitchGroup.png
  public/images/discordTextChannels/storageMonitor1.png
  public/images/discordTextChannels/storageMonitorContainer.png
  public/images/discordTextChannels/teamMemberInformation.png
  public/images/discordTextChannels/teamchatChannel.png
  public/images/discordTextChannels/trackerCreate.png
  public/images/discordTextChannels/trackersChannel.png
  public/images/discordTextChannels/unreachableDevice.png
  src/components/document/pages/discordTextChannels/applyCodeTag.tsx
  src/components/document/pages/discordTextChannels/discordTextChannelsSection.tsx
  src/data/documents/discordTextChannels/discordTextChannelsData.ts
  src/data/documents/discordTextChannels/images.ts
  src/pages/documents/discord-text-channels/index.tsx
  src/styles/globals.css
  src/types/discordTextChannelsDataTypes.ts
Labels: enhancement, approved

#47 create discord slash commands page
  public/images/discordSlashCommands/alarms_edit.png
  public/images/discordSlashCommands/alias.png
  public/images/discordSlashCommands/blacklist.png
  public/images/discordSlashCommands/cctv.png
  public/images/discordSlashCommands/craft.png
  public/images/discordSlashCommands/credentials.png
  public/images/discordSlashCommands/decay.png
  public/images/discordSlashCommands/help.png
  public/images/discordSlashCommands/item.png
  public/images/discordSlashCommands/leader.png
  public/images/discordSlashCommands/map.png
  public/images/discordSlashCommands/market.png
  public/images/discordSlashCommands/players.png
  public/images/discordSlashCommands/players_all_players.png
  public/images/discordSlashCommands/players_specific_user.png
  public/images/discordSlashCommands/recycle.png
  public/images/discordSlashCommands/research.png
  public/images/discordSlashCommands/reset.png
  public/images/discordSlashCommands/role.png
  public/images/discordSlashCommands/storagemonitor.png
  public/images/discordSlashCommands/switch.png
  public/images/discordSlashCommands/upkeep.png
  public/images/discordSlashCommands/uptime.png
  public/images/discordSlashCommands/voice.png
  src/components/document/pages/discordSlashCommands/section.tsx
  src/components/document/table/table.module.css
  src/data/documents/discordSlashCommands/images.ts
  src/pages/documents/commands/discord-slash-commands.tsx
Labels: enhancement

#39 Modify Flexible sidebar component
  public/icons/barsSolid.svg
  src/components/document/layout.tsx
  src/components/mainHeader/mainHeader.tsx
  src/components/modalBackground/modalBackground.module.css
  src/components/modalBackground/modalBackground.tsx
  src/components/sidebar/sidebar.module.css
  src/components/sidebarMenu/sidebarMenu.module.css
  src/components/sidebarMenu/sidebarMenu.tsx
  src/store/useSidebarStore.ts
Labels: enhancement, approved

#50 fix : urgently correct list order error
  src/components/document/pages/discordBotSetup/section.tsx
Labels: enhancement
